### ISSUE TITLE
Use Wrap Dependency system instead of hardcoded meson_options for PCRE

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#11]
See: https://mesonbuild.com/Wrap-dependency-system-manual.html

That's basically the way we should be doing, since it is exactly what [this change](https://github.com/expertisesolutions/efl/commit/375d205f192efda0653fab2eac1cc8fe917d7867#diff-2f0220d6614e01cb370018711bbe493a) is for.

**Comment by Coquinho** [comment]
@JPTIZ You have done it, right?

**Comment by JPTIZ** [comment]
Yes (not for OpenSSL, but that's a...distant plan. Really distant).
