### ISSUE TITLE
Enable tests at Windows CI

### ISSUE THREAD

**Issue by Coquinho** [expertisesolutions/efl#153]
By [enabling tests at Windows CI](https://github.com/expertisesolutions/efl/commit/bf7da8e020309c3e00c6a9bbfe50479aee7c73a9) this [error rises](https://github.com/expertisesolutions/efl/runs/780639995#step:23:192):
```
../src/tests/eina/eina_test_simple_xml_parser.c:80:F:Simple Xml Parser:eina_simple_xml_parser_node_dump:0: Assertion 'out == buf' failed: out == "<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="OpenStreetMap routing service" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <link href="http://tile.openstreetmap.nl/~lambertus/routing/index.html">
      <text>
        OpenStreetMap routing service
      </text>
    </li
```
For some reason `buf` seems to have a new line between every code line so differing from `out`. This doesn't happen on Linux builds, didn't happened when testing on the CI (with only eina enabled)

**Comment by JPTIZ** [comment]
This _may_ happen because of how Windows handles line-ends (LFCR, while in POSIX it is just a CR).

**Comment by Coquinho** [comment]
Yeah, that was my first thought too. But I couldn't found how to handle this. Do you have any ideas, @JPTIZ ?

**Comment by JPTIZ** [comment]
Here: https://github.com/expertisesolutions/efl/blob/f8b192989029693e9e315ca8cd780ead3ce5ebf6/src/lib/eina/eina_simple_xml_parser.c#L1106

We probably should change this to a `\r\n` when on Windows.

**Comment by Coquinho** [comment]
@JPTIZ All the others `\n` are ok?

**Comment by Coquinho** [comment]
At least changing only [that one](https://github.com/expertisesolutions/efl/runs/804172891) didn't work, later I will try changing them all.

**Comment by JPTIZ** [comment]
> At least changing only [that one](https://github.com/expertisesolutions/efl/runs/804172891) didn't work, later I will try changing them all.

:(

**Comment by Coquinho** [comment]
I will try it then.

**Comment by Coquinho** [comment]
#262 make every test on eina/evil work but know we have eo/eolian tests enabled too (those are not 100%). Do we want to add tests to CI now?

**Comment by JPTIZ** [comment]
> #262 make every test on eina/evil work but know we have eo/eolian tests enabled too (those are not 100%). Do we want to add tests to CI now?

Sure, why not?

**Comment by Coquinho** [comment]
I can think of 2 ways to do this, we can enable tests on our CI, and this will give us a lot of "CI failed" as some tests are still falling, or we can create a second CI that runs tests, as in #265, what you guys prefer?
For me, the second seems better because we know if the problem is about tests or build without seeing the log, but I don't have hard feelings here.

**Comment by JPTIZ** [comment]
> I can think of 2 ways to do this, we can enable tests on our CI, and this will give us a lot of "CI failed" as some tests are still falling, or we can create a second CI that runs tests, as in #265, what you guys prefer?
> For me, the second seems better because we know if the problem is about tests or build without seeing the log, but I don't have hard feelings here.

With the "`tests:`" job I recommended there, it would still be clear which one has failed (since e-mails and etc. would have the "tests:" tag on title and jobs are splitted in the sidebar, see the image below).
![image](https://user-images.githubusercontent.com/11988816/86626908-c8ed7f80-bf9d-11ea-9acf-f708bd1fcd36.png)

**Comment by Coquinho** [comment]
Wosh. this should be closed along time ago.
