### ISSUE TITLE
Evil tests are slow, so maybe evil functions are slow

### ISSUE THREAD

**Issue by cauebs** [expertisesolutions/efl#190]
We had to increase the time limit on the evil test suite so it wouldn't timeout. I checked and it's not getting stuck a single spot, it's really just slow all the way through. Functions like `getenv`, `setenv` and `realpath`, for example, appear to be taking too long to run.

It builds fine and tests still pass, so I'm not marking this as a bug, but it doesn't look right to me...

**Comment by vtorri** [comment]
strange. I can understand that setenv and realpath are taking time, but getenv is a function provided by Windows, so...

did you do some profiling ? either with Visual Studio or very sleepy ?
