### ISSUE TITLE
Eolian tests are broken again.

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#289]
See [this log](https://github.com/expertisesolutions/efl/runs/854801433#step:10:36) for detailed information:

```ninja
eolian: function 'a' not found in class 'Scope'
eolian: function 'a' not found in class 'Class_Funcs'
generating EFL_BETA_API_SUPPORT...
generating includes for <Eo.h> and "object_impl.eo.h"...
generating data type structure Object_Impl_Data...
generating function _object_impl_a_set...
generating function _object_impl_a_get...
generating function _object_impl_b_set...
generating function _object_impl_constructor_1...
generating function _object_impl_constructor_2...
generating function _object_impl_foo1...
generating function _object_impl_foo2...
generating function _object_impl_base_constructor...
generating function _object_impl_base_destructor...
generating function _object_impl_class_constructor...
generating function _object_impl_class_destructor...
removing includes for "object_impl.eo.c"
generating include for "object_impl.eo.c"
76%: Checks: 39, Failures: 9, Errors: 0

...

 3/25 eolian                    FAIL           2.22s (exit status 255 or signal 127 SIGinvalid)
```

**Comment by cauebs** [comment]
Tests appear to be failing in the `eolian_generation` test case. You may have actually cut the relevant part of the output there.

On some setups it fails because the command line built to call `eolian_gen` gets too long. It might actually not be a problem, so we should try removing the check in `eolian_generation.c`.

On the CI, it's failing when comparing the generated files to the ones in `src/tests/data/`. It might be related to line endings, as I wasn't able to reproduce it neither on my Windows nor my Linux setup.

**Comment by cauebs** [comment]
I just noticed you linked to the full log. Here are the relevant bits:
```
../src/tests/eolian/eolian_generation.c:110:F:Eolian Generation:eolian_types_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/typedef_ref.h", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:136:F:Eolian Generation:eolian_default_values_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/class_simple_ref.c", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:148:F:Eolian Generation:eolian_override_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/override_ref.c", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:91:F:Eolian Generation:eolian_dev_impl_code:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/object_impl_ref.c", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:160:F:Eolian Generation:eolian_functions_descriptions:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/class_simple_ref_eo.h", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:172:F:Eolian Generation:eolian_import:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/import_types_ref.h", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:184:F:Eolian Generation:eolian_docs:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/docs_ref.h", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:197:F:Eolian Generation:eolian_function_pointers:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/function_types_ref.h", output_filepath)' occurred
../src/tests/eolian/eolian_generation.c:230:F:Eolian Generation:owning:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/owning_ref.c", output_filepath)' occurred
```

**Comment by Coquinho** [comment]
> I just noticed you linked to the full log. Here are the relevant bits:
> 
> ```
> ../src/tests/eolian/eolian_generation.c:110:F:Eolian Generation:eolian_types_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/typedef_ref.h", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:136:F:Eolian Generation:eolian_default_values_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/class_simple_ref.c", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:148:F:Eolian Generation:eolian_override_generation:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/override_ref.c", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:91:F:Eolian Generation:eolian_dev_impl_code:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/object_impl_ref.c", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:160:F:Eolian Generation:eolian_functions_descriptions:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/class_simple_ref_eo.h", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:172:F:Eolian Generation:eolian_import:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/import_types_ref.h", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:184:F:Eolian Generation:eolian_docs:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/docs_ref.h", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:197:F:Eolian Generation:eolian_function_pointers:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/function_types_ref.h", output_filepath)' occurred
> ../src/tests/eolian/eolian_generation.c:230:F:Eolian Generation:owning:0: Failure '!_files_compare(TESTS_SRC_DIR"/data/owning_ref.c", output_filepath)' occurred
> ```
> 
> Basically, files don't match. It would be useful to see a diff, but the files generated aren't preserved after the tests have run.

Aren't we able to print the before deleting or something like that?

**Comment by cauebs** [comment]
> Aren't we able to print the before deleting or something like that?

Sure. Maybe even `system("diff ... ...")`.

**Comment by felipealmeida** [comment]
Vocês sabem que vocês podem rodar o programa manualmente né?

**Comment by felipealmeida** [comment]
outra opção é simplesmente imprimir na tela

**Comment by felipealmeida** [comment]
vocês podem alterar o teste pra depurar, só não fazer commit... joga num arquivo.. tem várias opções...

**Comment by cauebs** [comment]
I don't currently have a Windows environment to try and reproduce it, so I've been working with the CI to debug, yes. 

It seems it really is a problem with line endings. I suppose `it config core.autocrlf input` may just be enough. PR incoming.
