### ISSUE TITLE
Remove winpthreads dependency

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#3]
Currently, `pthread.h` is used in many files in EFL. Since no pthread library is available for Windows, a common workaround is to use Winpthreads.

Since we're aiming for native windows build, no pthread shall be used, so **native windows thread API** must be used when `WIN32` preprocessor directive is defined.

**Suggestions**

It is possible that some files in `evil` library already use it. Checking them could be a good start.

**Comment by caiosignor** [comment]
**pthread_testcancel** and **pthread_getcpuclockid**

I didn' t find a solution for this in win32

**Comment by Coquinho** [comment]
#15 implements synchronization besides:
- cond_timedwait on locks;
- Thread Local Storage functions.
