### ISSUE TITLE
Implement missing fnmatch function

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#30]
```c
int fnmatch(const char * a, const char * b, int c)
```

**Comment by vtorri** [comment]
regex and fnmath can be get from musl : 

https://github.com/vtorri/ewpi/blob/master/packages/regex/

**Comment by JPTIZ** [comment]
For regex, we used `pcre` (with a Wrap-Dependency straight from WrapDB: https://wrapdb.mesonbuild.com/pcre).

In order to use `fnmatch` from musl, would it require to replace that pcre dependency? Or we can pick musl's fnmatch implementation stand-alone?

**Comment by vtorri** [comment]
musl also provides regex stuff, so fnmatch + regex with few c files. so i would say, replace pcre with what i have done. e

**Comment by JPTIZ** [comment]
Okay, gonna check it then.
