### ISSUE TITLE
Check which VS is installed instead of assuming "Professional"

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#308]
Not everyone has VS Professional installed. I, for example, have Community only, but build scripts force the Professional directory.

We should check which one is installed before setting vcvars64 (or maybe ask the user to add it to path properly?).

**Comment by joaoantoniocardoso** [comment]
Maybe script it to try Professional, then Community?

**Comment by JPTIZ** [comment]
> 
> 
> Maybe script it to try Professional, then Community?

Could be a good approach, yes. Actually you gave me an additional idea: first check if vcvars64 is not available by default. If not, then check run for each version one by one.
