### ISSUE TITLE
Fix linkage issues

### ISSUE THREAD

**Issue by JPTIZ** [expertisesolutions/efl#31]
For some reason, `EAPI` is not being defined correctly to `__declspec(dllimport)`/`__declspec(dllexport)` when linking with `clang-cl`/`lld-link`.

**Comment by vtorri** [comment]
EFL_BUILD and DLL_EXPORT must be passed to the preprocessor. I have a fix in the EFL for eina and evil

[vtorri_dll.diff.gz](https://github.com/expertisesolutions/efl/files/4626228/vtorri_dll.diff.gz)

please apply it on a new efl repo without any of your fix and see if evil and eina compiles without any dllexport/dllimport problem

**Comment by vtorri** [comment]
voir
https://phab.enlightenment.org/D11834

**Comment by JPTIZ** [comment]
https://phab.enlightenment.org/D11939
