### ISSUE TITLE
Move unposix functions to evil

### ISSUE THREAD

**Issue by Coquinho** [expertisesolutions/efl#40]
Eina should contain wrappers to every function inexistent at Windows EFL, so
making EFL portable.

There are some dependencies that already work on `src/lib/evil/unposix`, those
should be rewritten, creating `eina_` wrappers that in case of a Windows build
calls our workaround/Windows function and in case of a Linux build calls the
original POSIX function. For now, those functions aren't portable because even
though they are implemented for Windows, using Windows API they have POSIX
signature, with POSIX names and as such they are expected to work as specified
by POSIX even on a Windows build.

The new dependencies should have this issue in mind, to avoid creating a lot of
future work.

The ideia is to create wrapper functions as:
```
EAPI <return type> 
eina_<function> (<arguments>)
{
#ifdef _WIN32
   // Implementation of the Windows workarround
   <windows implementation>
#else
   // Call to original POSIX function 
   <function> (<argumens>);
#endif
}
```

Why in Eina, you ask?
- To avoid creating a new lib at EFL;
- Because Eina is the lowest level lib of EFL;

For now, I don't when to create a new `eina_` file, wich file name patter we
should follow, when to put wrapper function on an existing `eina_` file, neither
how to group those new functions. Maybe have a lock on all eina files and see if
you can group the thing you are working on at an existing `eina_` file.

Even future work is to **poison** (probably using `meson`) those original
POSIX/WIN32API functions, forcing the use of our `eina_` function. Doing so, for
example, it should be impossible to an EFL programer's to call POSIX `sleep()`
and WIN32 `Sleep()` they should use an `eina_sleep()`.

### Update
In some cases, we can't write an `eina_` wrapper of a dependency because it is
used by `evil` and `eina` already depends on `evil` and that would make a cycle. In
this case, we should write an `evil_` wrapper, which means, we should apply the
same idea previously mentioned but using `evil` instead of `eina`. To illustrate:
```
EAPI <return type> 
evil_<function> (<arguments>)
{
#ifdef _WIN32
   // Implementation of the Windows workarround
   <windows implementation>
#else
   // Call to original POSIX function 
   <function> (<argumens>);
#endif
}
```

**Comment by JPTIZ** [comment]
We could start by listing which functions we want.

About categories, for now, I can think of:

- Filesystem-related functions;
- Process-related functions.

Other categories such as string-manipulation sound like internal helper functions, but we may review that.

**Comment by Coquinho** [comment]
@JPTIZ didn't get your category system.

**Comment by JPTIZ** [comment]
> @JPTIZ didn't get your category system.

The cate ate my arguments.

I was thinking about categories of things that could go to Eina, but forgot to type that into my response.

**Comment by Coquinho** [comment]
But why do we need to think in categories? I didn't get that.

**Comment by JPTIZ** [comment]
> But why do we need to think in categories? I didn't get that.

Nope, I was just expressing my line of thought.

**Comment by vtorri** [comment]
@Coquinho "Eina should contain wrappers to every function inexistent at Windows EFL, so
making EFL portable."

this is the very purpose of the existence of evil : 

if you add, for example mmap() implementation in eina, you have to create a function eina_mmap() and replace it, in all the code. In addition, the code will be slower on linux (one unnecessary call of eina_mmap() + mmap() call)

**Comment by cauebs** [comment]
>the code will be slower on linux (one unnecessary call of eina_mmap() + mmap() call)

@vtorri Honest question, what makes you think the compiler wouldn't inline that function?

**Comment by vtorri** [comment]
why would it inline it ? the heuristic is compiler dependent, it depends on the compiler  optimisation flags (-Os ? -O2 ? -O3 ? gcc ? clang ? icc ? vc++ ? etc...) So we can not be sure that the compiler would inline it

**Comment by JPTIZ** [comment]
We're going to move them to evil instead.

**Comment by JPTIZ** [comment]
Unposix is dead.


And so is this issue. RIP.
