### ISSUE TITLE
win32: clipboard not working

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#420]
The context menu `Text` (right-click inside a textbox) displays the option `Paste`, and if a text is selected, displays `Cut, Copy, Paste and Cancel`. Also, the clipboard functions can be used with the shortcuts `Ctrl+C` for **Copy** and `Ctrl+V` for **Paste**.

## Expected behavior
  - In some textbox:
    - `Ctrl+V` or `right-click -> Paste` should paste the clipboard to the textbox.
    - `Ctrl+C` or `right-click -> Copy` should copy the selected text of the textbox to the clipboard.

## Actual behavior
  - In some textbox:
    - `Ctrl+V` works as expected.
    - `right-click -> Paste` does paste the text from the clipboard to the textbox, but also throws the error:

```PowerShell
ERR:eina_safety ../src/lib/elementary/efl_ui_layout.c:1167 _efl_ui_layout_base_efl_layout_signal_signal_emit() safety check failed: efl_invalidated_get(obj) is true
ERR:eina_safety ../src/lib/evas/canvas/evas_focus.c:226 _efl_canvas_object_seat_focus_add() safety check failed: !efl_invalidating_get(eo_obj) && !efl_invalidated_get(eo_obj) is false
```
  - In some textbox:
    - `Ctrl+C` or `right-click -> Copy` does nothing to the clipboard and throws the error:

```PowerShell
ERR:eina_safety ../src/lib/ecore_evas/ecore_evas.c:5503 _deliver_cb() safety check failed: buffers == NULL
ERR:eina_safety ../src/modules/ecore_evas/engines/win32/ecore_evas_win32.c:1217 _delivery() safety check failed: ecore_win32_clipboard_set((Ecore_Win32_Window *)ee->prop.window, slice.mem, slice.len, mime_type) is false
```

## Steps to reproduce
In elementary_test:
  - open `Efl.Ui.Textbox`.
  - open another text editor.
  - try to transfer text from one to another using shortcuts.
  - try to transfer text from one to another using the context menu.

**Comment by joaoantoniocardoso** [comment]
Oh, I realize that there is a test that deals specifically with that: `Copy And Paste`, from `elementary_test`. So other way to reproduce this:

## Steps to reproduce
in elementary_test:
  - open `Copy And Paste`
  - Click `Copy from left entry` -> error message and the clipboard remains intact
```PowerShell
ERR:eina_safety ../src/lib/ecore_evas/ecore_evas.c:5503 _deliver_cb() safety check failed: buffers == NULL
ERR:eina_safety ../src/modules/ecore_evas/engines/win32/ecore_evas_win32.c:1217 _delivery() safety check failed: ecore_win32_clipboard_set((Ecore_Win32_Window *)ee->prop.window, slice.mem, slice.len, mime_type) is false
```
  - Click `Paste to left entry` -> paste if there is something in the clipboard
  - Click `Clear clipboard` -> error message, but cleans the clipboard
```PowerShell
ERR:eina_safety ../src/lib/ecore_evas/ecore_evas.c:5594 ecore_evas_selection_set() safety check failed: buffers->selection_buffer[buffer] == NULL is false
```
  - Click `Paste to left entry` -> error if there is nothing in the clipboard:
```PowerShell
ERR:elementary ../src/lib/elementary/elm_cnp.c:221 _callback_storage_error() Content cound not be received because of No fitting type could be found.
```

**Comment by felipealmeida** [comment]
Fixed by https://phab.enlightenment.org/D12166
