### ISSUE TITLE
win32: Code editor delay to show the entire content

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#421]
## Expected behavior
  - The textbox from the code editor should display all its content at once.

## Actual behavior
  - The textbox from the code editor displays only the first line. If the user interacts with the UI, then the remaining lines of the content are shown.

## Steps to reproduce
In elementary_test:
  - Open `Code Editor`.
  - Observe that only one line of the content is showed in the textbox.
  - Click in the UI (maybe several times).
  - Observe that other lines of the content are now being shown in the textbox.

**Comment by joaoantoniocardoso** [comment]
This behavior can be seen in Linux in the `Mirrored Editor` from `elementary_test` too: the editable textbox shows all the content but both mirrors show only the first line until further UI interaction.

**Comment by felipealmeida** [comment]
It is a timer that adds more lines if nothing gets typed by the user
