### ISSUE TITLE
win32: Minimize throws error message on console

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#422]
## Expected behavior
  - `Minimize` should minimize the window.

## Actual behavior
  - `Minimize` behaves as expected but also throws the following errors on the console:
```PowerShell
ERR:evas_main ../src/lib/evas/canvas/evas_render.c:3380 evas_render_updates_internal() viewport size != output size!
ERR:evas_main ../src/lib/evas/canvas/evas_render.c:3380 evas_render_updates_internal() viewport size != output size!
```

## Steps to reproduce
In elementary_test:
  - Click `Minimize`.
  - Observe the console output.

**Comment by Coquinho** [comment]
Just a note here, besides throwing errors at the console, it does minimize the window.

**Comment by joaoantoniocardoso** [comment]
#454 and #455 explains this behavior within an example.
