### ISSUE TITLE
elementary_tests.ext: Flip 2 doesn't show all its content

### ISSUE THREAD

**Issue by Coquinho** [expertisesolutions/efl#428]
## Current behavior
The list widget has an empty space above every menu item where it should have
little icons.
The text widget seems to show some formatting but it actually doesn't, and the
text seems to end abruptly.

## Expected behavior
The list widget has a menu on top that should show icons for each section:
`Hello` should be a left arrow; `Out` should be a right arrow; `There` should be
a home icon; `World` should be a refresh icon.
The other text widget should show some text effects like bold and italic (known issue
#419), and it should show more text, with emotions examples with different sizes and
a photo at the end.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open `Flip 2`
3. It will open on the list widget, where you may notice the empty gap
4. Click on any of the buttons at the bottom to change to the other widget
5. You should note how the text talks about formating but it doesn't show much,
  and how it ends abruptly

**Comment by felipealmeida** [comment]
works with fontconfig
