### ISSUE TITLE
elementary_tests.exe: Effects Efl.Animation.* fall at assert

### ISSUE THREAD

**Issue by Coquinho** [expertisesolutions/efl#429]
## Current behavior
The animations per se works but by clicking fast and many times at the button
that causes the animation it may raise an error like:
```
ERR:eina_safety ../src/lib/evas/canvas/efl_canvas_object_animation.c:42 _animator_cb() safety check failed: pd->in->run_start_time <= current is false
```

## Expected behavior
No errors to be thrown no matter how many time or how fast the button animation
is clicked.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open `Efl.Animation.Scale``
3. Press `Start Scale Animation to zoom {in/out}` many times
4. The error should appear at `cmd`, be aware that the application by itself do
print a lot.

**Comment by felipealmeida** [comment]
test doesnt consider animation still running
