### ISSUE TITLE
elementary_tests.exe: Efl.Animation.{Repeat/Start Delay} label covers buttons

### ISSUE THREAD

**Issue by Coquinho** [expertisesolutions/efl#431]
## Current behavior
Besides #429, the `Play Count/Start Delay` label cover both the right and left arrow
that should be used to set either the count or the delay, letting `click + hold +
slide` on the label as the only option to change those counts.

## Expected behavior
To be able to use the buttons as well as the `click + hold + slide` the label to change the
value as at master

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open `Efl.Animation.Repeat` or` `Efl.Animation.Start Delay`
3. Note that `Play Count/Start Delay` is a kinda bug, as if it was above something

**Comment by felipealmeida** [comment]
The test doesnt take in account the size with different fonts
