### ISSUE TITLE
elementary_tests: The button `Fields Update` doesn't work in the `Gengrid Update` test

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#451]
## Current behavior
On Windows, the button `Fields Update` doesn't work in the `Gengrid Update` test from `elementary_test`.

## Expected behavior
When clicking `Fields Update`, the selected Field Option should be updated on the checked grid items.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open `Gengrid Update`
3. Mark some grid item (could be multiple)
4. Mark some Field Options
5. Click `Fields Update`
6. Look for any change to the marked grid items in regard to the marked Field Options.

**Comment by felipealmeida** [comment]
Duplicate to #425
