### ISSUE TITLE
elementary_tests: Images from `Lists - Gengrid` category just vanish

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#452]
While the observed behavior is extended to almost all examples from elementary_tests with images, here it is easily shown with the `Lists - Gengrid` category, very simmilar to the #438.
  - Lists - Gengrid 
    - GenGrid
    - GenGrid 2
    - GenGrid Group
    - GenGrid Show/Bring_in
    - GenGrid Item Search by Text
    - GenGrid Item Styles
    - Gengrid Update Speed
    - GenGrid Focus
    - GenGrid Update
    - GenGrid Disabled Item Focus
    - GenGrid Item Custom Size

## Current behavior
On Windows, all the tests from the `Lists - Gengrid` category have a common problem: the images just vanish after some interaction (e.g.: scrolling). After ocurring the fist time, all images from next opened examples will not display. Obviously reopening elementary_tests will reset the behaviour. The category: 

## Expected behavior
When clicking `Fields Update`, the selected Field Option should be updated on the checked grid items.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open some of the Lists - Gengrid, e.g.: `Gengrid Update`
3. Scroll down/up util see some item without image
4. Observe the propagation of images vanishing while keep scrolling
5. Close and reopen the example (or any other example with images)
6. Note that any image / thumbnail will not be displayed anymore.

**Comment by felipealmeida** [comment]
duplicate to #425
