### ISSUE TITLE
elementary_tests: EFL.UI.Image Click doesn't detect clicks

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#453]
## Current behavior
On Windows, by clicking in the image or by pressing Return or Space keys `EFL.UI.Image Click` nothing happens.

## Expected behavior
When clicking `EFL.UI.Image Click`, the terminal should output a message containing a text like `0x400000a4c053 - clicked`.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open the test `EFL.UI.Image Click`
3. Click on the image, or press the `Return`/`Space` key from your keyboard
4. Observe the cmd.

**Comment by felipealmeida** [comment]
This is a bug in the test. The test instantiates a non-legacy component but tries to use a legacy event.
