### ISSUE TITLE
elementary_tests: `Iconify + Act` doesn't work in the `Window States` test

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#454]
## Current behavior
On Windows, when clicking on the button `Iconify + Act` from the `Window States` test, it minimizes and throws an error message:
```PowerShell
Iconify window. (current status: 0)
This window will be activated in 5 seconds.
FOC OUT
WIN FOCUS: focus,out
WIN FOCUS: unfocused
RESIZE - win geom:    0x   0
ERR:evas_main ../src/lib/evas/canvas/evas_render.c:3380 evas_render_updates_internal() viewport size != output size!
ERR:evas_main ../src/lib/evas/canvas/evas_render.c:3380 evas_render_updates_internal() viewport size != output size!
```
After 5 seconds it should restore with focus, but it doesn't:
```PowerShell
Activate window
ERR:ecore_win32 ../src/lib/ecore_win32/ecore_win32_window.c:1198 ecore_win32_window_focus() SetFocus() failed
```

Then if the window is restored using the window manager it shows the following messages, but its state isn't the same as the original, possibly causing some trouble with the next test executed (e.g. if you click `Iconify + Act` again, it will not minimize.
```PowerShell
FOC IN
WIN FOCUS: focus,in
WIN FOCUS: focused
RESIZE - win geom:  457x 495
```

## Expected behavior
When clicking on the button `Iconify + Act` from the `Window States` test, the window should be minimized and after 5 seconds, the minimized window should be restored with focus.

## Steps to reproduce
1. Run `elementary_tests.exe`
2. Open the test `Window States`
3. Click on the button `Iconify + Act`
4. Observe the cmd.

**Comment by vtorri** [comment]
i've fixed the error messages in https://phab.enlightenment.org/D12171

**Comment by vtorri** [comment]
D12176 fixed the remaining issue
