### ISSUE TITLE
No `clock_gettime()` implementation available for `_WIN32` at `src/tests/eina/eina_test_lock.c`.

### ISSUE THREAD

**Issue by joaoantoniocardoso** [expertisesolutions/efl#58]
Building in _WIN32, the test source `src/tests/eina/eina_test_lock.c` calls `clock_gettime()` _but there is no implementation available for `_WIN32`.

For linux, glibc implements `clock_gettime()` at `<time.h>` and for `__MACH__` `src/tests/eina/eina_test_lock.c` it self has an implementation using `<mach/clock.h>`.

note: I have no clue about the requirements for time precision.

**Comment by vtorri** [comment]
this should be replaced with high-resolution time stamps with win32

**Comment by felipealmeida** [comment]
Thanks vtorry

**Comment by vtorri** [comment]
do you want some code for that ?
